### PR TITLE
First attempt at making Search Module 'Fit'

### PR DESCRIPTION
**Pull request by DejaVu**
See what you think first. 
Some things may need tweaking/changing/clearing up.

Made a video to accompany this 
http://www.youtube.com/watch?v=_Rt0O3uQM9M

### CODE REVIEW

**Comment by DejaVu** [comment]
Just discovered another problem with this. 
Hiding the Search Module is not a great idea. Can it be moved off the page like Server Settings when pressing Alt-F?

Or perhaps it changes the Z-index to a minus (if possible)
Search Module Fault

**Comment by gugahoi** [comment]
it is moved off the page... top: 99999999 or something like that. I also found that bug a couple of days ago.

**Comment by DejaVu** [comment]
Would making it react the same as the Server Settings tab be a possibility. Still keeping the Alt-F for it to slide into view?

**Comment by DejaVu** [comment]
^^ Fix for the screenshot ;) ^^

**Comment by gugahoi** [comment]
Hey dude, i was going to merge this but i think it's better to wait till the search is merged om master as i believe there are going to be some changes...

**Pull request closed without merging**
