### PR TITLE
Change to onDeck poster img CSS

### PR DESCRIPTION
**Pull request by DarnisA**
I made a small change to the onDeck poster image CSS so it doesn't look stretched.

before:
before

after:
after

### CODE REVIEW

**Comment by gugahoi** [comment]
This doesnt work with movie posters that might have different aspect ratio are there too.

screen shot 2014-04-30 at 1 53 10 am

**Comment by DarnisA** [comment]
I've just noticed this as well. I'll get back to you with new code.

**Comment by DarnisA** [comment]
This should fix the problem.

**Comment by gugahoi** [comment]
Nice, thanks!

**Pull request merged**
