### PR TITLE
Search v3

### PR DESCRIPTION
**Pull request by DejaVu**
Can you check this before/if you merge it. 

I got the links working in the Server Settings drop down to NZBMatrix API and NZB.su and literally merged it with the current official master, but 109 commits seems a bit high to me seeing as you recently pulled from your origin/master - unless that was not upto date correctly perhaps?

I wanted to bring this back kicking and screaming as I think it will turn Maraschino on it's head and more users will be attracted to it purely for this. I've installed Maraschino on 4 mates machines purely on the strength of this module alone - albeit it was PiTA to merge at the time. :)

There was also a conflict since your recent changes, nothing major, but I pulled the changes in right, I think.

This works well for me, apart from the confusion for the search function in both NZB Search and Sickbeard's Add a Show function, both referred to as '#search' I think and they interfere with each other.

I'm hoping to rename the Sickbeard side to #sick_search hopefully.

I'm a feature freak and want to get all the hardwork everyones done into one organised Branch as á new 'experimental' I supposed, marked as major beta and 'unstable'.

### CODE REVIEW

**Comment by gugahoi** [comment]
Hey man, any chance you can make this pull request again? It's hard to tell what modifications you have done with 120 commits to get pulled.

I've been trying to find some time to get this polished too and if you have a look I did update to the lates master...

**Comment by DejaVu** [comment]
This was a fresh branch from mrk's master. The only commits that are mine are the bottom 3. 

The 2 above are the 2 you did to bring this up to date (Merge remote-tracking), not sure it worked as it was a pull from your original master - was that up to date when you merged it? The master has had a hard reset I think due to a mess up with proxy_images, but I'm not sure.

The ones above  from the midgetspy/format_bytes have all been pulled over for some reason. Not even sure why.
I can confirm though, that my Branch search-v3 is working (almost) perfectly if want to give it a go.

I think pulling this over again is just going to do the same thing, but I can give it a go.

**Comment by DejaVu** [comment]
Yep. Trying to Pull this again does the same thing.

**Comment by gugahoi** [comment]
Ok I'll have a look at the individual commits then and re code them if needed instead of merging this.

I just double checked and it seems it is up to date with upstream so might something weird going on.

**Pull request closed without merging**
